In [22]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import Sequential
from tensorflow.keras.applications.nasnet import NASNetMobile
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
import numpy as np

In [ ]:
!pip install tensorflow==2.2.0rc2

In [2]:
import tensorflow as tf
print(tf.__version__)

2.2.0-rc2


In [23]:
num_class = 5
def creat_compiled_model():
    model = Sequential()
    model.add(NASNetMobile(input_shape=(224, 224, 3), include_top=False,
                           weights='imagenet', pooling='avg'))
    model.add(Dense(num_class, activation='softmax'))
    model.layers[0].trainable = True
    model.layers[1].trainable = True
    sgd = SGD(learning_rate=0.01, momentum=0.01, nesterov=False)
    model.compile(optimizer=sgd, loss='hinge',  metrics=['accuracy'])
    return model

In [45]:
#model2 = creat_compiled_model()
model3 = creat_compiled_model()

In [24]:
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [25]:
# https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit_generator
train_datagen = ImageDataGenerator(rescale=1./255, preprocessing_function=preprocess_input)

In [21]:
train_generator = train_datagen.flow_from_directory('labelled_data', batch_size=4)

NameError: name 'train_datagen' is not defined

In [55]:
train_generator = train_datagen.flow_from_directory('labelled_data', batch_size=4)

Found 80 images belonging to 5 classes.


In [11]:
import numpy as np
import io
import logging
import json
import os
import hashlib
import requests
from PIL import Image

def download_ancien(url, output_dir, filename=None):
    # This function allows us to download a picture from a given url
    # It returns the file path of the downloaded image
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    if filename is None:
        filename = hashlib.md5(url.encode()).hexdigest()
    filepath = os.path.join(output_dir, filename)
    if os.path.exists(filepath):
        return filepath
    r = requests.get(url)
    r.raise_for_status()
    with io.open(filepath, mode='wb') as fout:
        fout.write(r.content)
    return filepath


def download(url, output_dir, filename=None):
    # This function allows us to download a picture from a given url
    # It returns the file path of the downloaded image
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    if filename is None:
        filename = hashlib.md5(url.encode()).hexdigest()
    filepath = os.path.join(output_dir, filename)
    if os.path.exists(filepath):
        im = Image.open(filepath)
        os.remove(filepath)
        filepath = os.path.join(output_dir, filename + ".jpg")
        im.save(filepath)
        return filepath
    r = requests.get(url)
    r.raise_for_status()
    with io.open(filepath, mode='wb') as fout:
        fout.write(r.content)
    im = Image.open(filepath)
    os.remove(filepath)
    filepath = os.path.join(output_dir, filename + ".jpg")
    im.save(filepath)
    return filepath

In [19]:
download("http://data.heartex.net/open-images/train_3/mini/32103a427a77b4bc.jpg", "./labelled_data/" )
download("http://data.heartex.net/open-images/train_0/mini/0158943da572415a.jpg", "./labelled_data/")

'./labelled_data/fc5895631440203a1531a73fbd7052cd.jpg'

In [20]:
download_ancien("http://data.heartex.net/open-images/train_3/mini/32103a427a77b4bc.jpg", "./labelled_data/" )
download_ancien("http://data.heartex.net/open-images/train_0/mini/0158943da572415a.jpg", "./labelled_data/")

'./labelled_data/fc5895631440203a1531a73fbd7052cd'

In [44]:
model3.fit(train_generator,epochs=2, steps_per_epoch=2 )

ValueError: Asked to retrieve element 0, but the Sequence has length 0

In [7]:
pred_labels, pred_scores = [], []
list_of_labels = ["Back", "Discard", "Front", "Left", "Right"]
image = load_img('./labelled_data/Front/00036.jpg', target_size=(224, 224))
image = img_to_array(image)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
# cette ligne a verifier le self?
probs = model3.predict(image)[0]
print(probs)
label_idx = np.argmax(probs)
label = list_of_labels[label_idx]
score = probs[label_idx]
pred_labels.append(label)
pred_scores.append(score.item())
print(pred_labels)
print(pred_scores)

[1.3450172e-04 7.6691277e-04 2.7236246e-04 8.3852404e-01 1.6030219e-01]
['Left']
[0.8385240435600281]


In [ ]:
model3.layers[2].trainable = False

In [11]:
import os 
path = os.path.join("labelled_data", "trained_model")
#model3.layers[0].trainable = False
#model3.layers[1].trainable = False
model3.save(path,save_format="tf")

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: labelled_data/trained_model/assets


In [12]:
import os 
path = os.path.join("labelled_data", "trained_model")
loaded_model = load_model(path)

In [13]:
pred_labels, pred_scores = [], []
list_of_labels = ["Back", "Discard", "Front", "Left", "Right"]
image = load_img('./labelled_data/Front/00036.jpg', target_size=(224, 224))
image = img_to_array(image)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
# cette ligne a verifier le self?
probs = loaded_model.predict(image)[0]
print(probs)
label_idx = np.argmax(probs)
label = list_of_labels[label_idx]
score = probs[label_idx]
pred_labels.append(label)
pred_scores.append(score.item())
print(pred_labels)
print(pred_scores)

[1.2880607e-06 1.8086722e-03 1.3093783e-06 9.9807203e-01 1.1667530e-04]
['Left']
[0.9980720281600952]


In [11]:
model3.summary()
mm = model3.layers[0]

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
NASNet (Model)               (None, 1056)              4269716   
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 5285      
Total params: 4,275,001
Trainable params: 4,238,263
Non-trainable params: 36,738
_________________________________________________________________


In [6]:
import os 
path = os.path.join("labelled_data", "model")
model3.save(path, overwrite=True, include_optimizer=False,save_format='h5')

https://www.tensorflow.org/api_docs/python/tf/keras/Model#save

In [8]:
mod = load_model("labelled_data/model",compile=False)
#mod.summary()


In [63]:
pred_labels, pred_scores = [], []
list_of_labels = ["Back", "Discard", "Front", "Left", "Right"]
image = load_img('./labelled_data/Front/00044.jpg', target_size=(224, 224))
image = img_to_array(image)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
# cette ligne a verifier le self?
probs = mod.predict(image)[0]
print(probs)
label_idx = np.argmax(probs)
label = list_of_labels[label_idx]
score = probs[label_idx]
pred_labels.append(label)
pred_scores.append(score.item())
print(pred_labels)
print(pred_scores)

[3.0930175e-06 7.0649298e-07 1.0134218e-07 9.9999607e-01 3.4672703e-12]
['Left']
[0.9999960660934448]


In [64]:
pred_labels, pred_scores = [], []
list_of_labels = ["Back", "Discard", "Front", "Left", "Right"]
image = load_img('./labelled_data/Front/00044.jpg', target_size=(224, 224))
image = img_to_array(image)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
# cette ligne a verifier le self?
probs = model3.predict(image)[0]
print(probs)
label_idx = np.argmax(probs)
label = list_of_labels[label_idx]
score = probs[label_idx]
pred_labels.append(label)
pred_scores.append(score.item())
print(pred_labels)
print(pred_scores)

[3.0930175e-06 7.0649298e-07 1.0134218e-07 9.9999607e-01 3.4672703e-12]
['Left']
[0.9999960660934448]


In [29]:
print(model3.optimizer.get_config())


{'name': 'SGD', 'learning_rate': 0.01, 'decay': 0.0, 'momentum': 0.01, 'nesterov': False}


NameError: name 'loss' is not defined

In [26]:
print(mod.optimizer.get_config() == model3.optimizer.get_config())
print(mod.optimizer.get_gradients() == model3.optimizer.get_gradients())

True


TypeError: get_gradients() missing 2 required positional arguments: 'loss' and 'params'

In [ ]:
tf.saved_model.save(model3,"labelled_data")

In [ ]:
loaded = tf.saved_model.load("labelled_data")
modd = build_model(loaded)


In [ ]:
pred_labels, pred_scores = [], []
list_of_labels = ["Back", "Discard", "Front", "Left", "Right"]
image = load_img('./labelled_data/Front/00036.jpg', target_size=(224, 224))
image = img_to_array(image)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
# cette ligne a verifier le self?
probs = modd.predict(image)[0]
print(probs)
label_idx = np.argmax(probs)
label = list_of_labels[label_idx]
score = probs[label_idx]
pred_labels.append(label)
pred_scores.append(score.item())
print(pred_labels)
print(pred_scores)

In [ ]:
loaded_model = load_model(path)

In [ ]:
pred_labels, pred_scores = [], []
list_of_labels = ["Back", "Discard", "Front", "Left", "Right"]
image = load_img('./labelled_data/Front/00036.jpg', target_size=(224, 224))
image = img_to_array(image)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
# cette ligne a verifier le self?
probs = loaded_model.predict(image)[0]
print(probs)
label_idx = np.argmax(probs)
label = list_of_labels[label_idx]
score = probs[label_idx]
pred_labels.append(label)
pred_scores.append(score.item())
print(pred_labels)
print(pred_scores)

In [ ]:
loaded_model = load_model(path)

In [ ]:
loaded_model = load_model(path, compile=False)
pred_labels, pred_scores = [], []
list_of_labels = ["Back", "Discard", "Front", "Left", "Right"]
image = load_img('/c/Users/yfakihan/workspace/POC/POC1/car_dataset/cars_test/00025.jpg', target_size=(224, 224))
image = img_to_array(image)
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))
# cette ligne a verifier le self?
probs = loaded_model.predict(image)[0]
print(probs)
label_idx = np.argmax(probs)
label = list_of_labels[label_idx]
score = probs[label_idx]
pred_labels.append(label)
pred_scores.append(score.item())
print(pred_labels)
print(pred_scores)

In [ ]:
print(loaded_model)

----------------------
----------------------

In [1]:
import logging
from logging.handlers import RotatingFileHandler

In [2]:
# création de l'objet logger qui va nous servir à écrire dans les logs
logger = logging.getLogger()
# on met le niveau du logger à DEBUG, comme ça il écrit tout
logger.setLevel(logging.DEBUG)


# création d'un formateur qui va ajouter le temps, le niveau
# de chaque message quand on écrira un message dans le log
formatter = logging.Formatter('%(asctime)s :: %(levelname)s :: %(message)s')
# création d'un handler qui va rediriger une écriture du log vers
# un fichier en mode 'append', avec 1 backup et une taille max de 1Mo
file_handler = RotatingFileHandler('labelled_data/activity.log', 'a', 1000000, 1)
# on lui met le niveau sur DEBUG, on lui dit qu'il doit utiliser le formateur
# créé précédement et on ajoute ce handler au logger
file_handler.setLevel(logging.DEBUG)
file_handler.setFormatter(formatter)
logger.addHandler(file_handler)
# création d'un second handler qui va rediriger chaque écriture de log
# sur la console
stream_handler = logging.StreamHandler()
stream_handler.setLevel(logging.DEBUG)
logger.addHandler(stream_handler)

In [3]:
# Après 3 heures, on peut enfin logguer
# Il est temps de spammer votre code avec des logs partout :
#logger.info('Hello')
#logger.warning('Testing %s', 'foo')
logger.debug("this is a fucking message !")


this is a fucking message !


In [4]:
logger.debug("I am coming home, coming home, all ....")
logger.error("Le nombre de sous dossier est differents du nombre de classe ")

I am coming home, coming home, all ....
Le nombre de sous dossier est differents du nombre de classe 


In [54]:
import os

number_of_folders = 0
number_of_files = 0
for _, dirnames, filnames in os.walk("./labelled_data/"):
    number_of_folders += len(dirnames)
    number_of_files += len(filnames)
print(f"the number of folders is : {number_of_folders}")
print(f"the number of files is : {number_of_files}")

the number of folders is : 5
the number of files is : 86


In [6]:
open("./labe")

FileNotFoundError: [Errno 2] No such file or directory: './labe'

In [7]:
open("imaginary.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'imaginary.txt'

In [21]:
number_of_folders = 4
if number_of_folders != 5:
    raise FileNotFoundError ('The number of sub directories is differents from the number of classes ')

FileNotFoundError: The number of sub directories is differents from the number of classes 

In [12]:
from PIL import Image
im = Image.open('labelled_data/33ddec51ed102878.jpeg')
im.save('test.jpg')

In [13]:
import os
os.remove('labelled_data/33ddec51ed102878.jpeg')